name: build-on-push
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NASM
      uses: ilammy/setup-nasm@v1.5.1
      with:
        version: 2.10.07
        platform: win32
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
    - name: Build Debug|Win32
      run: msbuild .\rekkrunchy.sln /p:Configuration=Debug /p:Platform=Win32
    - name: Build Release|Win32
      run: msbuild .\rekkrunchy.sln /p:Configuration=Release /p:Platform=Win32
